[versions]
# Fabric
minecraft = "1.21.1"
yarn = "1.21.1+build.3"
loader = "0.16.10"
fabric_api = "0.116.9+1.21.1"

# Carpt
carpet = "1.4.147"

# Libraries
okhttp = "4.12.0"
gson = "2.10.1"
slf4j = "2.0.9"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
fabric-loom = { id = "fabric-loom", version = "1.9-SNAPSHOT" }
